name: Deploy to WP Engine
on:
  push:
    branches:
     - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v3
      with:
      
      # Deploy vars
        WPE_ENV: martaonline
        REMOTE_PATH: "wp-content/plugins/marta-plugin/"
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
